version: 2
jobs:
  build:
    working_directory: ~/aquahub
    docker:
      - image: openjdk:8
    environment:
      SBT_VERSION: 1.1.2
    steps:
      - run: echo 'export ARTIFACT_BUILD=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip' >> $BASH_ENV
      - run:
          name: Get sbt binary
          command: |
                    apt update && apt install -y curl
                    curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
                    dpkg -i sbt-$SBT_VERSION.deb
                    rm sbt-$SBT_VERSION.deb
                    apt-get update
                    apt-get install -y sbt python-pip git
                    #pip install awscli
                    #apt-get clean && apt-get autoclean
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - restore_cache:
          key: sbt-cache
      - run:
          name: Compile & Test
          command: |
                    cd aquahub
                    cat /dev/null | sbt clean update test
      - run:
          name: dist package
          command: |
                    cd aquahub
                    cat /dev/null | sbt docker:publishLocal
      - store_artifacts:
          path: aquahub/aquahub/server/target/universal/server-0.1.0-SNAPSHOT.zip
          destination: server-0.1.0-SNAPSHOT
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
      - deploy:
          command: |
              #mv server/target/universal/server-0.1.0-SNAPSHOT.zip $CIRCLE_ARTIFACTS/$ARTIFACT_BUILD
              #aws s3 cp $CIRCLE_ARTIFACTS/$ARTIFACT_BUILD s3://samplescala.blogs/builds/ --metadata {\"git_sha1\":\"$CIRCLE_SHA1\"}
