-- MySQL Script generated by MySQL Workbench
-- Thu Nov 29 21:34:50 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aquahub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aquahub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aquahub` DEFAULT CHARACTER SET utf8 ;
USE `aquahub` ;

-- -----------------------------------------------------
-- Table `aquahub`.`article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aquahub`.`article` ;

CREATE TABLE IF NOT EXISTS `aquahub`.`article` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `article_id` CHAR(65) NOT NULL,
  `url` VARCHAR(500) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `body` TEXT NOT NULL,
  `publish_datetime` DATETIME NULL DEFAULT current_timestamp,
  `force_update` BIT NOT NULL DEFAULT 0,
  UNIQUE INDEX `article_id_UNIQUE` (`article_id` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
